apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: java-deploymen 
spec: 
  selector: 
    matchLabels: 
      app: java 
  replicas:  {{ .Values.replicaCount }}
  template:
    metadata: 
      labels: 
        app: java 
    spec: 
      containers: 
      - name: java 
        image: {{ .Values.jenkinsmaven.image.repository }}:{{ .Values.jenkinsmaven.image.tag }}
        ports: 
        - containerPort: 8080
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}    
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: java-servic 
spec: 
  selector: 
    app: java 
  ports: 
  - protocol: TCP 
    port: {{ .Values.jenkinsmaven.image.port }}
    targetPort: {{ .Values.jenkinsmaven.image.targetPort }} 
  type: LoadBalancer 
