apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: myapp-deployment 
spec: 
  selector: 
    matchLabels: 
      app: myapp 
  replicas: {{ .Values.replicaCount }} 
  template:
    metadata: 
      labels: 
        app: myapp
    spec: 
      containers: 
      - name: myapp
        image: {{ .Values.myapp.image.repository }}:{{ .Values.myapp.image.tag }}
        ports: 
        - containerPort: 8081
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}     
---
kind: Service 
apiVersion: v1 
metadata: 
  name: myapp-service 
spec: 
  selector: 
    app: myapp 
  ports: 
  - protocol: TCP 
    port: {{ .Values.myapp.image.port }}
    targetPort: {{ .Values.myapp.image.targetPort }} 
  type: LoadBalancer 
