replicaCount: 1
imagePullSecrets: autodeploy
jenkinsmaven:
  image:
    repository: autodeploy.azurecr.io/csandhya8/springbootmavenjunitsample
    tag: #{Release.Artifacts._csandhya8_springbootmavenjunitsample.BuildId}#
    port: 80
    targetPort: 80
myapp:
  image:
    repository: autodeploy.azurecr.io/csandhya8/spring-boot-maven-example-helloworld
    tag: #{Release.Artifacts._csandhya8_spring-boot-maven-example-helloworld.BuildId}#
    port: 8081
    targetPort: 8081
